// Available languages
export const Languages = [
	{ key: 2, label: 'English', code: 'en', isRTL: false, isDefault: false },
	{ key: 1, label: 'العربية', code: 'ar', isRTL: true, isDefault: true },
];

// English
export const en = {
	NoInternetConnection: 'No Internet Connection',
	// signup
	signup_title: 'Create an account',
	signup_username_input: 'Name',
	signup_email_input: 'Email',
	signup_password_input: 'Password',
	signup_password_retype_input: 'Retype Password',
	signup_btn: 'Sign Up',
	signup_have_acc: 'Have an account?',
	privacy_one: 'By signing up you agree to our',
	privacy_two: 'Terms of use',
	privacy_three: 'Privacy Policies ✌🏻',
	// Phone verification
	Phone_verification_title: "what's your phone number?",
	Phone_verification_phone_input: 'Phone Number',
	Phone_verification_verify_btn: 'Verify',
	Phone_verification_skip: 'Skip this step',
	Phone_verification_tip: "Your phone number will be secured, We'll never spam you.",
	// Login
	EmailOrPhone: 'Email or phone number',
	Password: 'Password',
	Login: 'Login',
	ForgotPass: 'Forgot Password',
	SkipLogin: 'Skip',
	CreateAccount: 'Create Account',
	// code confirmation
	Enter_verification_code: 'Enter the verification code',
	Resend: 'Resend Code',
	// confirme pw
	new_password_title: 'Set a new password',
	new_password_sec_input: 'Password confirmation',
	new_password_btn: 'Done',
	Save: 'Save',
	Unspecified: 'Unspecified',
	Male: 'Male',
	Female: 'Female',
	Gender: 'Gender',
	Bio: 'Bio',
	BirthDate: 'Birth Date',
	Cancel: 'Cancel',
	Done: 'Done',
	SearchBarText: 'Search',
	ChangePass: 'Change password',
	ChangeEmail: 'Change email',
	ChangePhone: 'Change phone',
	// Drawer
	DrawerItem_Home: 'Home',
	DrawerItem_Settings: 'Settings',
};

// Arabic
export const ar = {
	NoInternetConnection: 'غير مُتصل بالانترنت',
	signup_title: 'انشئ حساب مجاني',
	signup_username_input: 'الاسم',
	signup_email_input: 'البريد الإلكتروني',
	signup_password_input: 'كلمة المرور',
	signup_password_retype_input: 'أعد إدخال كلمة المرور',
	signup_btn: 'تسجيل',
	signup_have_acc: 'لديك حساب؟',
	privacy_one: 'من خلال تسجيلك فإنك توافق على',
	privacy_two: 'شروط الاستخدام',
	privacy_three: 'سياسات الخصوصية ✌🏻',
	Phone_verification_title: 'ما هو رقم هاتفك؟',
	Phone_verification_phone_input: 'رقم الهاتف',
	Phone_verification_verify_btn: 'تفعيل',
	Phone_verification_skip: 'تخطي هذه الخطوة',
	Phone_verification_tip: 'سيتم تأمين رقم هاتفك ، لن نرسل لك أي محتوى غير مرغوب فيه مطلقًا.',
	// Login
	EmailOrPhone: 'الايميل او رقم الجوال',
	Password: 'كلمة المرور',
	Login: 'تسجيل الدخول',
	ForgotPass: 'نسيت كلمة المرور',
	SkipLogin: 'تخطي',
	CreateAccount: 'انشاء حساب',
	// code confirmation
	Enter_verification_code: 'ادخل كود التفعيل',
	Resend: 'اعد ارسال الكود',
	new_password_title: 'اعادة تعين كلمة المرور',
	new_password_sec_input: 'تأكيد كلمة المرور',
	new_password_btn: 'تأكيد',
	Save: 'حفظ',
	Unspecified: 'غير محدد',
	Male: 'ذكر',
	Female: 'انثى',
	Gender: 'الجنس',
	Bio: 'نبذة عنك',
	BirthDate: 'تاريخ الميلاد',
	Cancel: 'الغاء',
	Done: 'تم',
	SearchBarText: 'بحث',
	ChangePass: 'تغيير كلمة المرور',
	ChangeEmail: 'تغيير البريد الالكتروني',
	ChangePhone: 'تغيير رقم الجوال',
	//Drawer
	DrawerItem_Home: 'الرئيسية',
	DrawerItem_Settings: 'الاعدادات',
};