# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rosnamah' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Rosnamah
pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  target 'Rosnamah-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RosnamahTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Rosnamah-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  

  

end
